test: 1
map:
  code: azerty
  name: test://{{ env.CODE:TEST_DEFAULT_VALUE }}
  array:
    - test://{{ env.CODE:OTHER_VALUE }}
    - test://{{ env.CODE }}
rabbit:
  hosts:
    - "{{env.CODE}}"
values: "{{ env.CODE2 }}"
templates:
  - name: test
    value: "HELLO"
  - name: test2
    value: "BIJOUR {{ env.HELLO }}"
  - name: test3
    value: "{{ env.HELLO }}"
